### ISSUE TITLE
Make the class reference table sortable

### ISSUE THREAD

**Issue by TechnoPorg** [godotengine/doc-status#27]
For aspiring documentation contributors such as myself, the doc status page is a helpful tool for identifying areas that could use some love. I've especially used it to identity 0% documented classes that I can tackle.
To this end, it would be helpful if the columns of the table could be made sortable, in order to more quickly find classes with no docs overall, no description, etc.
A plugin like DataTables or a custom JS sorting function would do the job nicely. If this is a desired change, I would be happy to implement it!

**Comment by Calinou** [comment]
> A plugin like DataTables or a custom JS sorting function would do the job nicely. If this is a desired change, I would be happy to implement it!

Sounds good, but I'd prefer a custom JS sorting function as opposed to DataTables. (Our dataset isn't huge, and I'd rather not add a large dependency.)
